### ISSUE TITLE
Add QuestionModel

### ISSUE THREAD

**Issue by kacus** [kacus/CC-StarWarsQuiz#5]
### Question Model Specification 
**Question Model represents one question in game, so it contains one correct answer and three unique randomly selected answers.**

- [x] **constructor(type, id)**
'type' determines one of three questions(about people, vehicles or star-ships).
'id' is object id in SWAPI we are asking for. We want to define it on creation object phase, because we want to control uniqueness of questions in the appropriate Controller.

- [x] **fetchData()**
init model with data

- [x] **getType()**
return type of question

- [x] **getAnswers()**
return a list of answers. First one is the correct answer. By the answer we understand pair id-name, where each id is unique.
Wrong answers are chosen randomly and are unique inside question.

- [x] **getCorrectAnswer()**
return pair id-name of correct answer.

- [ ] **selectAnswer(id)**
set user answer

- [ ] **answerIsCorrect()**
return true if user answer is correct otherwise return false

**Comment by cwaniakobezczel** [comment]
selectAnswer(id) ma zwracać parę [id,name] ?

**Comment by kacus** [comment]
selectAnswer nic nie zwraca, ustawia tylko odpowiedz uzytkownika
> this.userAnswer = id
